build: {}
dependencies:
    combined: example.com-combined-combined
    random: example.com-random-random1
    segmented: example.com-segmented-example-2
    simple: example.com-simple-example
extract: {}
sources:
    example:
        description: description
        url: http://example.com
views: {}
