build: {}
dependencies: {}
sources:
    example:
        description: Simple Random CSV data
        url: http://public.source.civicknowledge.com.s3.amazonaws.com/example.com/simple-example-altnames.csv
views: {}
