build: {}
dependencies:
    random: example.com-random-random1
    simple: example.com-simple-example
extract: {}
sources:
    example1:
        description: The First Example File
        url: http://ds-public.civicknowledge.org.s3.amazonaws.com/example.com/example1.csv
    example2:
        description: The Second Example File
        url: http://ds-public.civicknowledge.org.s3.amazonaws.com/example.com/example2.csv
views: {}
