build: {}
dependencies: {}
extract: {}
sources:
    example:
        description: Random CSV data
        url: http://public.source.civicknowledge.com.s3.amazonaws.com/example.com/simple-example.csv
views: {}
