build: {}
dependencies: {}
sources:
    StatePriceIndicesAndQ:
        description: None
        row_spec:
            data_end_line: 75
            data_start_line: 27
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 11
            - 12
            - 13
            - 14
            - 15
            - 16
            - 17
            header_lines:
            - 20
            - 21
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Price_Indicies_and_Implicit_Quantities/StatePriceIndicesAndQ.xls
    farm_output:
        comment: null
        conversion: null
        dd_url: null
        description: Indices of farm output, input, and total factor productivity
            for the United States, 1948-2011. Includes price indices and implicit
            quantities of farm outputs and inputs (see second tab in workbook), Table1a.
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 7
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
            - 6
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/National_Tables/table01.xls
    table01:
        description: Indices of farm output, input, and total factor productivity
            for the United States, 1948-2011. Includes price indices and implicit
            quantities of farm outputs and inputs (see second tab in workbook), Table1a.
        row_spec:
            data_end_line: 71
            data_start_line: 7
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
            - 6
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/National_Tables/table01.xls
    table02:
        description: None
        row_spec:
            data_end_line: 5
            data_start_line: 4
            header_comment_lines:
            - 0
            - 1
            header_lines:
            - 2
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/National_Tables/table02.xls
    table03:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table03.xls
    table03_growth:
        description: None
        row_spec:
            data_start_line: 57
            header_comment_lines:
            - 56
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table03.xls
    table04:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table04.xls
    table05:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table05.xls
    table06:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table06.xls
    table07:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table07.xls
    table08:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table08.xls
    table09:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table09.xls
    table10:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table10.xls
    table11:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table11.xls
    table12:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table12.xls
    table13:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table13.xls
    table14:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table14.xls
    table15:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table15.xls
    table16:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table16.xls
    table17:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table17.xls
    table18:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table18.xls
    table19:
        description: None
        row_spec:
            data_end_line: 53
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Total_Factor_Productivity/table19.xls
    table20:
        description: None
        row_spec:
            data_end_line: 56
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            header_lines:
            - 7
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/State_Ranking_Tables_/table20.xls
    table21:
        description: None
        row_spec:
            data_end_line: 56
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            header_lines:
            - 7
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/State_Ranking_Tables_/table21.xls
    table22:
        description: None
        row_spec:
            data_end_line: 56
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            header_lines:
            - 7
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/State_Ranking_Tables_/table22.xls
views: {}
