build:
    requirements: {}
dependencies: {}
sources:
    StatePriceIndicesAndQ:
        comment: null
        conversion: null
        dd_url: null
        description: None
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 27
            header_comment_lines:
            - 0
            - 1
            header_lines:
            - 22
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Price_Indicies_and_Implicit_Quantities/StatePriceIndicesAndQ.xls
    capital_input:
        comment: null
        conversion: null
        dd_url: null
        description: Capital input (excluding land)
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table08.xls
    chemical_input:
        comment: null
        conversion: null
        dd_url: null
        description: Agricultural chemical input
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table15.xls
    crop_output:
        comment: null
        conversion: null
        dd_url: null
        description: Crop output
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table04.xls
    energy_input:
        comment: null
        conversion: null
        dd_url: null
        description: Energy input
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table14.xls
    farm_output:
        comment: null
        conversion: null
        dd_url: null
        description: Indices of farm output, input, and total factor productivity
            for the United States, 1948-2011. Includes price indices and implicit
            quantities of farm outputs and inputs (see second tab in workbook), Table1a.
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 71
            data_start_line: 7
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            header_lines:
            - 5
            - 6
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/National_Tables/table01.xls
    farm_output_prices:
        comment: null
        conversion: null
        dd_url: null
        description: Indices of farm output, input, and total factor productivity
            for the United States, 1948-2011. Includes price indices and implicit
            quantities of farm outputs and inputs (see second tab in workbook), Table1a.
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 71
            data_start_line: 7
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            header_lines:
            - 5
            - 6
        segment: 3
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/National_Tables/table01.xls
    fertilizer_consumption:
        comment: null
        conversion: null
        dd_url: null
        description: Fertilizer consumption
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table17.xls
    growth_sources:
        comment: null
        conversion: null
        dd_url: null
        description: Sources of growth in the U.S. farm sector (average annual rates),
            1948-2011. Includes decomposition into quantity and quality of inputs.
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 22
            data_start_line: 4
            header_comment_lines:
            - 0
            - 1
            header_lines:
            - 2
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/National_Tables/table02.xls
    hired_labor:
        comment: null
        conversion: null
        dd_url: null
        description: Hired labor
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table11.xls
    input_growth:
        comment: null
        conversion: null
        dd_url: null
        description: States ranked by level and growth of inputs
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            header_lines:
            - 7
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/State_Ranking_Tables_/table21.xls
    intermediate_output:
        comment: null
        conversion: null
        dd_url: null
        description: Total intermediate input
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table13.xls
    labor_input:
        comment: null
        conversion: null
        dd_url: null
        description: Total labor input
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table10.xls
    land_input:
        comment: null
        conversion: null
        dd_url: null
        description: Land input
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table09.xls
    livestock_ouput:
        comment: null
        conversion: null
        dd_url: null
        description: Livestock output
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table05.xls
    other_inputs:
        comment: null
        conversion: null
        dd_url: null
        description: Other intermediate inputs
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table18.xls
    output_growth:
        comment: null
        conversion: null
        dd_url: null
        description: States ranked by level and growth of farm output
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            header_lines:
            - 7
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/State_Ranking_Tables_/table20.xls
    pesticide_consumption:
        comment: null
        conversion: null
        dd_url: null
        description: Pesticide consumption
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table16.xls
    productivity_growth:
        comment: null
        conversion: null
        dd_url: null
        description: States ranked by level and growth of productivity
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            header_lines:
            - 7
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/State_Ranking_Tables_/table22.xls
    related_output:
        comment: null
        conversion: null
        dd_url: null
        description: Other farm-related output
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table06.xls
    total_factor:
        comment: null
        conversion: null
        dd_url: null
        description: Indices of total factor productivity by State
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Total_Factor_Productivity/table19.xls
    total_input:
        comment: null
        conversion: null
        dd_url: null
        description: Total farm input by State
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table07.xls
    total_output:
        comment: null
        conversion: null
        dd_url: null
        description: Total farm output by State
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Outputs/table03.xls
    unpaid_labor:
        comment: null
        conversion: null
        dd_url: null
        description: Self-employed and unpaid family labor
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_end_line: 55
            data_start_line: 8
            header_comment_lines:
            - 0
            - 1
            - 2
            - 3
            - 4
            header_lines:
            - 5
        url: http://www.ers.usda.gov/datafiles/Agricultural_Productivity_in_the_US/StateLevel_Tables_Relative_Level_Indices_and_Growth_19602004Inputs/table12.xls
views: {}
